name: macOS Install & Train

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  macos:
    # 同时在 Apple Silicon (macos-14) 和 Intel (macos-13) 跑
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14, macos-13]
        python-version: ["3.10", "3.11"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Prepare macOS build tools (可按需增减)
        run: |
          brew update
          # 需要系统依赖/编译工具时在这里加：
          # brew install cmake libomp pkg-config swig

      - name: Upgrade pip & install deps
        env:
          MPLBACKEND: Agg  # 若你会画图，CI 环境无显示器，强制无头后端
        run: |
          python -m pip install -U pip wheel
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "requirements.txt not found" && exit 1
          fi

      - name: Train
        env:
          MPLBACKEND: Agg
          PYTORCH_ENABLE_MPS_FALLBACK: "1"  # 若用 PyTorch，在 Apple 芯片上无 MPS 时回退 CPU
        run: |
          python train.py

      - name: Upload training artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scores-${{ matrix.os }}-py${{ matrix.python-version }}
          path: |
            scores/**
            **/*.log
          if-no-files-found: ignore
